e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls"), name='home'),
    path('users/', include("users.urls"), name='users'),
    path('orders/', include("orders.urls"), name='orders'),
]

orders/urls.py
from django.urls import path
from .views import create_order, all_orders
app_name = 'orders'
urlpatterns = [
    path('create-order/<slug:slug>', create_order, name='create_order'),
    path('orders/', all_orders, name='all-orders'),
    path('my-orders/', all_orders, name='my-orders')
]

products/urls.py
from django.urls import path
from products import views as product_views
from orders import views as order_views  # Импортируем представления из модуля orders

app_name = 'products'
urlpatterns = [
    path('', product_views.home_page, name='index'),
    path('products/<slug:slug>/', product_views.detail_page, name='detail'),
    path('products/<slug:slug>/reviews/<int:id>/', product_views.delete_review, name='delete_review'),
    path('products/<slug:slug>/edit_review/<int:id>/', product_views.edit_review, name='edit_review'),
    path('create-product/', product_views.create_product, name='create_product'),
    # path('orders/', order_views.orders_list, name='orders_list'),  # Указываем на представление orders_list из модуля orders
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('logout/', views.logout_page, name='logout'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ search_query }}">
        <button class="btn btn-outline-success" type="submit">Search</button>
          {% if request.user.is_authenticated %}
              {% if request.user.is_staff %}
                  <a href="{% url 'orders:all-orders' %}" class="btn btn-warning ms-3">All Orders</a>
                  <a href="{% url 'products:create_product' %}" class="btn btn-warning ms-3">Create Product</a>
              {% endif %}
              <a href="{% url 'orders:my-orders' %}" class="btn btn-warning ms-3">My orders</a>
              <a href="{% url 'users:logout' %}" class="btn btn-warning ms-3">Logout</a>
          {% else %}
            <a href="{% url 'users:register' %}" class="btn btn-success mx-3">Register</a>
            <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
          {% endif %}
      </form>
    </div>
  </div>
</nav>
  {% block content %}
  
  {% endblock %}

    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


  </body>
</html>

templates/create_order.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <h3>{{ product.name }}</h3>
                <form method="post" class="form-conterol">
                    {% csrf_token %}
                    <label for="quantity">Mahsulot soni:</label>
                    <input type="number" id="quantity" name="quantity">
                    <label for="address">Mahsulot yetkazib berilishi kerak bo'lgan adres:</label>
                    <input type="text" id="address" name="address">
                    
                    <button class="btn btn-primary">Buyurtmani tasdiqlash</button>
                </form>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/create_product.html
{% extends 'base.html' %}

{% block title %}Edit review{% endblock %}

{% block content %}

    <form method="POST" class="form-control" enctype="multipart/form-data">
    
        {% csrf_token %}
    
        {{ form.as_p }}
    
        <button class="btn btn-warning" type="submit">Create_product</button>
    </form>

{% endblock %}

templates/edit_review.html
{% extends 'base.html' %}

{% block title %}Edit review{% endblock %}

{% block content %}

    <form method="POST" class="form-control">
    
        {% csrf_token %}
    
        {{ form.as_p }}
    
        <button class="btn btn-warning" type="submit">Edit review</button>
    </form>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>E commerce website</h1>
    <div class="container">
        <div class="col-md-12 p-5">
            <div class="row">
                {% for product in products %}
                    <div class="card" style="width: 18rem;">
                        <img src="{{ product.product_image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <a href="{% url 'products:detail' product.slug %}">
                                <h5 class="card-title">{{ product.name }}</h5>
                            </a>
                            <p class="card-text">{{ product.description }}</p>
                            <a href="#" class="btn btn-primary">Buy</a>
                            <span class="ms-5 fw-bolder">${{ product.price }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="col-md-12 p-5">
            <form method="POST">
                {% csrf_token %}
                {{ login_form }}
                <button class="btn btn-primary" type="submit">Login</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/orders_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Orders List</title>
</head>
<body>
    <h1>Orders List</h1>
    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>User</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            {% if order.user == request.user %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.user.username }}</td>
                    <td>{{ order.product.name }}</td>
                    <td>{{ order.quantity }}</td>
                    <td>{{ order.status }}</td>
                </tr>
            {% else %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.user.username }}</td>
                <td>{{ order.product.name }}</td>
                <td>{{ order.quantity }}</td>
                <td>{{ order.status }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/product_detail.html
{% extends 'base.html' %}

{% block title %}Detail page{% endblock %}

{% block content %}

    <div class="container">
        <div class="col-md-12 py-5">
            <h1>{{ product.name }}</h1>
            <div class="row py-5">
                <div class="col-md-4">
                    <img src="{{ product.product_image.url }}" alt="{{ product.name }}">
                </div>
                <div class="col-md-4 card">
                    <h3>{{ product.description }}</h3>
                </div>
                <div class="col-md-4 card">
                    <h3>{{ product.price }}</h3>
                    <p>Standart yetkazib berish
                        Manzilga qarab 4 soatdan 3 kungacha yetkazib beriladi</p>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'orders:create_order' product.slug %}" class="btn btn-success">Buyurtma
                            berish</a>
                    {% else %}
                        <h3>Buyurtma berish uchun ro'yxatdan o'ting</h3>
                        <a href="{% url 'users:register' %}" class="btn btn-primary">Register</a>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                {% if request.user.is_authenticated %}
                    <div class="col-md-6">
                        <form class="form-control" action="" method="post">
                            {% csrf_token %}
                            <textarea name="review" id="review" cols="52" rows="3"></textarea>
                            <br>
                            <button class="btn btn-primary" type="submit">Send Review</button>
                        </form>
                    </div>
                {% else %}
                    <div class="col-md-4">
                        <p>Siz review qoldirish uchun ro'yxatdan o'tgan bo'lishingiz kerak</p>
                        <a href="{% url 'users:login' %}" class="btn btn-success">Login</a>
                    </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <ul class="list-group list-group-flush">
                        {% for review in product_reviews %}
                            <li class="list-group-item">
                                <h5>{{ review.user.username }} | {{ review.created_at }}
                                    <a class="btn btn-warning"
                                       href="{% url 'products:edit_review' product.slug review.id %}">edit</a>
                                    <a class="btn btn-danger"
                                       href="{% url 'products:delete_review' product.slug review.id %}">del</a>
                                </h5>
                                <p>{{ review.review }}</p>
                            </li>
                        {% endfor %}
                    </ul>

                </div>
            </div>

        </div>
    </div>


{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="col-md-12 p-5">
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary mt-3" type="submit">Sign Up</button>
                <a href="{% url 'users:login' %}" class="btn btn-warning ms-3 mt-3">Login</a>
            </form>
        </div>
    </div>


{% endblock %}